### ISSUE TITLE
Additional parameters.

### ISSUE THREAD

**Issue by kslen** [syncore/qclauncher#10]
Hey.

--set /Config/CONFIG/isLowViolence 1 --set /Config/CONFIG/isLowResParticles 1 is a thing from what I can gather from forums. Any interest in adding them to the launcher?

**Comment by syncore** [comment]
I haven't worked on this in a long time (basically since QC moved to Steam), and wasn't sure if either of these flags actually did anything back when I first wrote this utility so I probably won't get around to adding them. However, I did design the application in such a way that you can specify additional parameters that I have not specifically included in the UI.

If you want to use isLowViolence and/or isLowResParticles, check the README under the section:

> **New game options have been found since the last QCLauncher release, how can I try these new options?** 

```
Since version 1.01, it has been possible to pass custom Quake Champions start-up options to QCLauncher with the --customargs flag. For example, create a shortcut to QCLauncher or start QCLauncher in this manner:

qclauncher.exe --customargs="--set /Config/CONFIG/isLowViolence 1 --set /Config/CONFIG/isLowResParticles 1"

QCLauncher will then pass these options to Quake Champions on launch.
```
