### ISSUE TITLE
does not work :(

### ISSUE THREAD

**Issue by qogrodnik** [syncore/qclauncher#13]
[qclauncher.log](https://github.com/syncore/qclauncher/files/2284241/qclauncher.log)

**Comment by syncore** [comment]
Please try now and report back whether it is still broken. This is very likely caused by some Bethesda backend API changes that were noticed in Issue #12 about a month and a half ago. The fix in that issue should address this and it should work now after I just changed a setting to use the new API. Requesting confirmation whether this has fixed it. I will look into it further in a few hours if it did not fix it.

**Comment by qogrodnik** [comment]
It's working again. Thanks for fix and very nice tool.
