### ISSUE TITLE
Unable to get required hardware fingerprint from Bethesda Launcher

### ISSUE THREAD

**Issue by bruh4315** [syncore/qclauncher#18]
i did everything correctly .exe path and credentials.im using the latest version of the qc launcher.

**Comment by syncore** [comment]
Download the [fingerprint tool](https://github.com/syncore/blff/releases/tag/v0.1) separately and run `blffconsole.exe` via command prompt as follows: `blffconsole.exe -r=5 -d=12 -e` and check the results.

If it finds the fingerprint, copy it, and then you can start qclauncher with `qclauncher.exe --fp="your-fingerprint-here"`

It has been a few years since I have been involved in Quake -- I am not sure if Bethesda still validates the fingerprint, so you might be able to still launch with `qclauncher.exe --fp="fingerprintValue"` and use any fake value for fingerprintValue.
