### ISSUE TITLE
Ignore "Auto-start QC and exit QCLauncher" when holding shift-key

### ISSUE THREAD

**Issue by PredatH0r** [syncore/qclauncher#5]
Instead of having to delete the config file, please allow a user to enter the GUI mode again when he holds the shift key while QClauncher starts, basically like a shift+double click on the desktop shortcut

**Comment by syncore** [comment]
It's currently possible to bring up the UI by starting qclauncher with the `-show` argument instead of having to delete the configuration file. I could probably add support for holding down the SHIFT key, but I am concerned that this will block the start-up process for at least 2 seconds. I can investigate this later this week
