### ISSUE TITLE
Suggestion: Additional start options

### ISSUE THREAD

**Issue by InfernalRabbit** [syncore/qclauncher#9]
- Hide weapon: --set /Config/CONFIG/WeaponZScale -10 
- Other optimizations: --set /Config/CONFIG/isLowResParticles 1

**Comment by syncore** [comment]
This has been implemented since version 1.01. Create a shortcut to qclauncher or start it in the following manner using the `--customargs` flag:

`qclauncher.exe --customargs="--set /Config/CONFIG/WeaponZScale -10 --set /Config/CONFIG/isLowResParticles 1"`

I have updated the README file on the repository page and have added this information
